# Generated by Django 5.1.2 on 2024-10-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repositories'},
        ),
        migrations.RenameField(
            model_name='commit',
            old_name='respository',
            new_name='repository',
        ),
        migrations.AlterField(
            model_name='commit',
            name='hash',
            field=models.CharField(default='68659f560ceb32b2480a808974760ef87206a44e', max_length=40),
        ),
    ]
